AllowedHosts: "*"
WithOrigins:
  - "*"
Url: ""
DefaultServerProvider: "Tencent"
Replace:
  Url:
    - ["http://", "https://"]
    - ["ws.stream.qqmusic.qq.com", "dl.stream.qqmusic.qq.com"]
  Pic:
    - ["http://", "https://"]